/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package GJ's library.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the enumeration Genre.
 * 
 * @generated
 */
public enum Genre {
	/**
	 * The documentation of the enumeration literal GENRE.
	 * 
	 * @generated
	 */
	GENRE,
	
	/**
	 * The documentation of the enumeration literal GENRE.
	 * 
	 * @generated
	 */
	GENRE,
	
	/**
	 * The documentation of the enumeration literal GENRE.
	 * 
	 * @generated
	 */
	GENRE,
	
}
