/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package GJ's library.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class LibraryItem
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class LibraryItem {
	/**
	 * The documentation of the attribute title.
	 * 
	 * @generated
	 */
	private String title;
	
	/**
	 * The documentation of the attribute libraryId.
	 * 
	 * @generated
	 */
	private String libraryId;
	
	/**
	 * The documentation of the attribute genre.
	 * 
	 * @generated
	 */
	private Genre genre;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public LibraryItem() {
		super();
	}
	/**
	 * The documentation of the getter getTitle.
	 * 
	 * @generated
	 */
	public String getTitle() {
		return this.title;
	}
	
	/**
	 * The documentation of the setter setTitle.
	 * 
	 * @generated
	 */
	public void setTitle(String newTitle) {
		this.title = newTitle;
	}
	
	/**
	 * The documentation of the getter getLibraryId.
	 * 
	 * @generated
	 */
	public String getLibraryId() {
		return this.libraryId;
	}
	
	/**
	 * The documentation of the setter setLibraryId.
	 * 
	 * @generated
	 */
	public void setLibraryId(String newLibraryId) {
		this.libraryId = newLibraryId;
	}
	
	/**
	 * The documentation of the getter getGenre.
	 * 
	 * @generated
	 */
	public Genre getGenre() {
		return this.genre;
	}
	
	/**
	 * The documentation of the setter setGenre.
	 * 
	 * @generated
	 */
	public void setGenre(Genre newGenre) {
		this.genre = newGenre;
	}
}
