/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package GJ's library.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Magazine
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Magazine extends LibraryItem {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Magazine() {
		super();
	}
	/**
	 * The documentation of the method issue.
	 * 
	 * @return
	 * 
	 * @generated
	 */
	public String issue() {
		// Start of user code for the body of issue
		// TODO should be implemented
		return null;
		// End of user code
	}
}
