/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package GJ's library.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Video
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Video extends LibraryItem {
	/**
	 * The documentation of the attribute runtime.
	 * 
	 * @generated
	 */
	private Integer runtime;
	
	/**
	 * The documentation of the attribute director.
	 * 
	 * @generated
	 */
	private String director;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Video() {
		super();
	}
	/**
	 * The documentation of the method duration.
	 * 
	 * @return
	 * 
	 * @generated
	 */
	public String duration() {
		// Start of user code for the body of duration
		// TODO should be implemented
		return null;
		// End of user code
	}
	
	
	/**
	 * The documentation of the getter getRuntime.
	 * 
	 * @generated
	 */
	public Integer getRuntime() {
		return this.runtime;
	}
	
	/**
	 * The documentation of the setter setRuntime.
	 * 
	 * @generated
	 */
	public void setRuntime(Integer newRuntime) {
		this.runtime = newRuntime;
	}
	
	/**
	 * The documentation of the getter getDirector.
	 * 
	 * @generated
	 */
	public String getDirector() {
		return this.director;
	}
	
	/**
	 * The documentation of the setter setDirector.
	 * 
	 * @generated
	 */
	public void setDirector(String newDirector) {
		this.director = newDirector;
	}
}
