<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Library">
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headLibrarian" ordered="false"
        lowerBound="1" eType="#//Librarian" containment="true" eOpposite="#//Librarian/libraryHeadLibrarian"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staff" ordered="false"
        upperBound="-1" eType="#//Librarian" containment="true" eOpposite="#//Librarian/libraryStaff"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patrons" ordered="false"
        upperBound="-1" eType="#//Patron" containment="true" eOpposite="#//Patron/registeredLibrary"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catalog" ordered="false"
        upperBound="-1" eType="#//Publication" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Librarian">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraryHeadLibrarian" ordered="false"
        eType="#//Library" eOpposite="#//Library/headLibrarian"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraryStaff" ordered="false"
        eType="#//Library" eOpposite="#//Library/staff"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Patron">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registeredLibrary" ordered="false"
        eType="#//Library" eOpposite="#//Library/patrons"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checkouts" ordered="false"
        upperBound="-1" eType="#//Publication" eOpposite="#//Publication/checkedOutBy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Publication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checkedOutBy" ordered="false"
        upperBound="-1" eType="#//Patron" eOpposite="#//Patron/checkouts"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
